import { useState, useEffect } from "react";
import Head from "next/head";
import swal from "sweetalert";
import styles from "../styles/Home.module.css";
import Navbar from "../Components/Navbar";
export default function Home() {
  const [cart, setCart] = useState({});
  const [subTotal, setSubTotal] = useState(0);
  const [key1, setKey1] = useState(0);
  useEffect(() => {
    try {
      if (localStorage.getItem("cart")) {
        setCart(JSON.parse(localStorage.getItem("cart") || "{}"));
      }
    } catch (error) {
      console.error(error);
      localStorage.clear();
    }
  }, []);

  const saveCart = (myCart) => {
    localStorage.setItem("cart", JSON.stringify(myCart));
    let subt = 0;
    let keys = Object.keys(myCart);
    for (let i = 0; i < keys.length; i++) {
      subt += Math.round(
        (myCart[keys[i]]["price"] *
          myCart[keys[i]]["qty"] *
          (100 - myCart[keys[i]]["discount"])) /
          100
      );
    }
    setSubTotal(subt);
  };

  const addToCart = (itemCode, qty, price, name, discount) => {
    let newCart = JSON.parse(JSON.stringify(cart));
    if (itemCode in cart) {
      newCart[itemCode].qty = cart[itemCode].qty + qty;
    } else {
      newCart[itemCode] = { qty: 1, price, name, discount };
    }
    setKey1((prevKey) => prevKey + 1);
    setCart(newCart);
    saveCart(newCart);
  };
  const removeFromCart = (itemCode, qty, price, name, discount) => {
    let newCart = JSON.parse(JSON.stringify(cart));
    if (itemCode in cart) {
      newCart[itemCode].qty = cart[itemCode].qty - qty;
    }
    if (newCart[itemCode]["qty"] <= 0) {
      delete newCart[itemCode];
    }
    setKey1((prevKey) => prevKey + 1);
    setCart(newCart);
    saveCart(newCart);
  };
  const clearCart = () => {
    setCart({});
    saveCart({});
  };
  return (
    <div className="bg-amber-50">
      <Head>
        <title>Cart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/carts.ico" />
      </Head>
      <Navbar
        cart={cart}
        addToCart={addToCart}
        removeFromCart={removeFromCart}
        subTotal={subTotal}
        clearCart={clearCart}
        key1={key1}
      />
      <div className="h-screen bg-amber-50 m-5">
        <ol className="grid grid-cols-3 justify-center">
          <li>
            <div className="flex m-2">
              <div className=" flex flex-col p-6 w-5/6 h-full  rounded-lg shadow-lg  bg-white ">
                <h5 className="text-gray-900 text-xl leading-tight font-medium mb-2">
                  Lighting Celing Kitchen
                </h5>
                <p className="text-gray-800 text-base mb-4 flex flex-col">
                  <span className="font-bold">
                    Price: <span className="font-normal">30</span>
                  </span>
                  <span className="font-bold">
                    Discount: <span className="font-normal">14.89%</span>
                  </span>
                </p>
                <button
                  onClick={() => {
                    swal({
                      title: "Item added",
                      icon: "success",
                    });
                    addToCart(96, 1, 30, "lighting ceiling kitchen", 14.89);
                  }}
                  type="button"
                  className=" inline-block px-4 py-3 bg-blue-500 text-white font-medium text-sm leading-tight rounded shadow-md shadow-gray-400 hover:bg-blue-800 hover:shadow-lg focus:bg-blue-800 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out"
                >
                  Add to cart
                </button>
              </div>
            </div>
          </li>

          <li>
            <div className="flex m-2 ">
              <div className=" flex flex-col p-6 w-5/6 h-full rounded-lg shadow-lg bg-white ">
                <h5 className="text-gray-900 text-xl leading-tight font-medium mb-2">
                  Black Motorbike
                </h5>
                <p className="text-gray-800 text-base mb-4 flex flex-col">
                  <span className="font-bold">
                    Price: <span className="font-normal">569</span>
                  </span>
                  <span className="font-bold">
                    Discount: <span className="font-normal">13.63%</span>
                  </span>
                </p>
                <button
                  onClick={() => {
                    swal({
                      title: "Item added",
                      icon: "success",
                    });
                    addToCart(91, 1, 569, "Black Motorbike", 13.63);
                  }}
                  type="button"
                  className=" inline-block px-4 py-3 bg-blue-500 text-white font-medium text-sm leading-tight rounded shadow-md shadow-gray-400 hover:bg-blue-800 hover:shadow-lg focus:bg-blue-800 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out"
                >
                  Add to cart
                </button>
              </div>
            </div>
          </li>
          <li>
            <div className="flex m-2 ">
              <div className=" flex flex-col p-6 w-5/6 h-full rounded-lg shadow-lg  bg-white ">
                <h5 className="text-gray-900 text-xl leading-tight font-medium mb-2">
                  Infinix INBOOK
                </h5>
                <p className="text-gray-800 text-base mb-4 flex flex-col">
                  <span className="font-bold">
                    Price: <span className="font-normal">1099</span>
                  </span>
                  <span className="font-bold">
                    Discount: <span className="font-normal">11.83%</span>
                  </span>
                </p>
                <button
                  onClick={() => {
                    swal({
                      title: "Item added",
                      icon: "success",
                    });
                    addToCart(9, 1, 1099, "Infinix INBOOK", 11.83);
                  }}
                  type="button"
                  className=" inline-block px-4 py-3 bg-blue-500 text-white font-medium text-sm leading-tight rounded shadow-md shadow-gray-400 hover:bg-blue-800 hover:shadow-lg focus:bg-blue-800 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out"
                >
                  Add to cart
                </button>
              </div>
            </div>
          </li>
          <li>
            <div className="flex m-2 ">
              <div className=" flex flex-col p-6 w-5/6 h-full rounded-lg shadow-lg  bg-white ">
                <h5 className="text-gray-900 text-xl leading-tight font-medium mb-2">
                  Hyaluronic Acid Serum
                </h5>
                <p className="text-gray-800 text-base mb-4 flex flex-col">
                  <span className="font-bold">
                    Price: <span className="font-normal">19</span>
                  </span>
                  <span className="font-bold">
                    Discount: <span className="font-normal">13.31%</span>
                  </span>
                </p>
                <button
                  onClick={() => {
                    swal({
                      title: "Item added",
                      icon: "success",
                    });
                    addToCart(16, 1, 19, "Hyaluronic Acid Serum", 13.31);
                  }}
                  type="button"
                  className=" inline-block px-4 py-3 bg-blue-500 text-white font-medium text-sm leading-tight rounded shadow-md shadow-gray-400 hover:bg-blue-800 hover:shadow-lg focus:bg-blue-800 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out"
                >
                  Add to cart
                </button>
              </div>
            </div>
          </li>
          <li>
            <div className="flex m-2  ">
              <div className=" flex flex-col p-6 w-5/6 h-full rounded-lg shadow-lg  bg-white ">
                <h5 className="text-gray-900 text-xl leading-tight font-medium mb-2">
                  Pubg Printed Graphic T-Shirt
                </h5>
                <p className="text-gray-800 text-base mb-4 flex flex-col">
                  <span className="font-bold">
                    Price: <span className="font-normal">46</span>
                  </span>
                  <span className="font-bold">
                    Discount: <span className="font-normal">16.44%</span>
                  </span>
                </p>
                <button
                  onClick={() => {
                    swal({
                      title: "Item added",
                      icon: "success",
                    });
                    addToCart(54, 1, 46, "Pubg Printed Graphic T-Shirt", 16.44);
                  }}
                  type="button"
                  className=" inline-block px-4 py-3 bg-blue-500 text-white font-medium text-sm leading-tight rounded shadow-md shadow-gray-400 hover:bg-blue-800 hover:shadow-lg focus:bg-blue-800 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out"
                >
                  Add to cart
                </button>
              </div>
            </div>
          </li>
        </ol>
      </div>
    </div>
  );
}
